#!/usr/bin/env python3
"""PreToolUse hook: Block access to Tuist-generated Xcode project files.

.xcworkspace and .xcodeproj are generated by `tuist generate`.
Reading or editing them directly is wasteful and error-prone.

Exit codes: 0 = allow, 2 = block (stderr message shown)
"""

import json
import sys

BLOCKED_EXTENSIONS = (".xcworkspace", ".xcodeproj")
MESSAGE = (
    "This file is generated by Tuist. "
    "Do not read or edit .xcworkspace/.xcodeproj files directly. "
    "Edit Project.swift or Tuist/ configs instead, then run `tuist generate`."
)


def main():
    try:
        input_data = json.load(sys.stdin)
    except json.JSONDecodeError:
        sys.exit(0)

    tool_input = input_data.get("tool_input", {})
    file_path = tool_input.get("file_path", "") or tool_input.get("filePath", "")

    for ext in BLOCKED_EXTENSIONS:
        # Check if the path contains .xcworkspace/ or .xcodeproj/ (inside the bundle)
        # or ends with the extension itself
        if f"{ext}/" in file_path or f"{ext}\\" in file_path or file_path.endswith(ext):
            print(f"\u26a0\ufe0f {MESSAGE}", file=sys.stderr)
            sys.exit(2)

    sys.exit(0)


if __name__ == "__main__":
    main()
